function out1 = jac_xd_f(t)
%JAC_XD_F
%    OUT1 = JAC_XD_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    22-Sep-2025 19:11:35

out1 = [(((real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0)./(real(cos(t./5.0))-imag(sin(t./5.0)))+(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*(imag(cos(t./5.0))+real(sin(t./5.0))).*1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2).*(real(cos(t./5.0))-imag(sin(t./5.0))).^2)./((real(cos(t./5.0))-imag(sin(t./5.0))).^2+(imag(cos(t./5.0))+real(sin(t./5.0))).^2);0.0];
