function out1 = x_ddot_d_f(t)
%X_DDOT_D_F
%    OUT1 = X_DDOT_D_F(T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    22-Sep-2025 20:49:19

et1 = -(imag(cos(t./5.0))./2.5e+1+real(sin(t./5.0))./2.5e+1)./(real(cos(t./5.0))-imag(sin(t./5.0)))+1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2.*(real(cos(t./5.0))./2.5e+1-imag(sin(t./5.0))./2.5e+1).*(imag(cos(t./5.0))+real(sin(t./5.0)))+1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^3.*(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).^2.*(imag(cos(t./5.0))+real(sin(t./5.0))).*2.0;
et2 = 1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2.*(real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0).*(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*2.0;
et3 = (real(cos(t./5.0))-imag(sin(t./5.0))).^2.*((real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0)./(real(cos(t./5.0))-imag(sin(t./5.0)))+1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2.*(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*(imag(cos(t./5.0))+real(sin(t./5.0))));
et4 = -((real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0).*(imag(cos(t./5.0))+real(sin(t./5.0))).*2.0-(real(cos(t./5.0))-imag(sin(t./5.0))).*(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*2.0).*1.0./((imag(cos(t./5.0))+real(sin(t./5.0))).^2+(real(cos(t./5.0))-imag(sin(t./5.0))).^2).^2;
et5 = ((real(cos(t./5.0))-imag(sin(t./5.0))).^2.*(et1+et2))./((imag(cos(t./5.0))+real(sin(t./5.0))).^2+(real(cos(t./5.0))-imag(sin(t./5.0))).^2)+et3.*et4;
et6 = ((real(cos(t./5.0))-imag(sin(t./5.0))).*(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*((real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0)./(real(cos(t./5.0))-imag(sin(t./5.0)))+1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2.*(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*(imag(cos(t./5.0))+real(sin(t./5.0)))).*-2.0)./((imag(cos(t./5.0))+real(sin(t./5.0))).^2+(real(cos(t./5.0))-imag(sin(t./5.0))).^2);
out1 = [et5+et6,0.0];
end
