function out1 = x_ddot_d_f(t)
%X_DDOT_D_F
%    OUT1 = X_DDOT_D_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    22-Sep-2025 19:28:26

et1 = -(imag(cos(t./5.0))./2.5e+1+real(sin(t./5.0))./2.5e+1)./(real(cos(t./5.0))-imag(sin(t./5.0)))+(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*(real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0).*1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2.*2.0+(real(cos(t./5.0))./2.5e+1-imag(sin(t./5.0))./2.5e+1).*(imag(cos(t./5.0))+real(sin(t./5.0))).*1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2;
et2 = (imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).^2.*(imag(cos(t./5.0))+real(sin(t./5.0))).*1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^3.*2.0;
et3 = 1.0./((real(cos(t./5.0))-imag(sin(t./5.0))).^2+(imag(cos(t./5.0))+real(sin(t./5.0))).^2).^2.*((real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0)./(real(cos(t./5.0))-imag(sin(t./5.0)))+(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*(imag(cos(t./5.0))+real(sin(t./5.0))).*1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2).*(real(cos(t./5.0))-imag(sin(t./5.0))).^2;
et4 = -((real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0).*(imag(cos(t./5.0))+real(sin(t./5.0))).*2.0-(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*(real(cos(t./5.0))-imag(sin(t./5.0))).*2.0);
et5 = ((real(cos(t./5.0))-imag(sin(t./5.0))).^2.*(et1+et2))./((real(cos(t./5.0))-imag(sin(t./5.0))).^2+(imag(cos(t./5.0))+real(sin(t./5.0))).^2);
et6 = ((imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*((real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0)./(real(cos(t./5.0))-imag(sin(t./5.0)))+(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*(imag(cos(t./5.0))+real(sin(t./5.0))).*1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2).*(real(cos(t./5.0))-imag(sin(t./5.0))).*-2.0)./((real(cos(t./5.0))-imag(sin(t./5.0))).^2+(imag(cos(t./5.0))+real(sin(t./5.0))).^2)+et3.*et4;
out1 = [et5+et6,0.0];
