function out1 = x_dot_d_f(t)
%X_DOT_D_F
%    OUT1 = X_DOT_D_F(T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    22-Sep-2025 20:49:19

out1 = [((real(cos(t./5.0))-imag(sin(t./5.0))).^2.*((real(cos(t./5.0))./5.0-imag(sin(t./5.0))./5.0)./(real(cos(t./5.0))-imag(sin(t./5.0)))+1.0./(real(cos(t./5.0))-imag(sin(t./5.0))).^2.*(imag(cos(t./5.0))./5.0+real(sin(t./5.0))./5.0).*(imag(cos(t./5.0))+real(sin(t./5.0)))))./((imag(cos(t./5.0))+real(sin(t./5.0))).^2+(real(cos(t./5.0))-imag(sin(t./5.0))).^2),0.0];
end
