function time_varying_goal = x_ref_f(t)
%X_REF_F
%    TIME_VARYING_GOAL = X_REF_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    22-Sep-2025 19:11:34

time_varying_goal = [cos(t./5.0).*(3.0./2.0),sin(t./5.0).*(3.0./2.0)];
