function out1 = xd_f(t)
%XD_F
%    OUT1 = XD_F(T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    22-Sep-2025 20:49:19

out1 = [pi./2.0+atan2(sin(t./5.0),cos(t./5.0))-atan2(sqrt(-(cos(t./5.0).^2.*(9.0./8.0)+sin(t./5.0).^2.*(9.0./8.0)-1.0).^2+1.0),cos(t./5.0).^2.*(9.0./8.0)+sin(t./5.0).^2.*(9.0./8.0)),acos(cos(t./5.0).^2.*(9.0./8.0)+sin(t./5.0).^2.*(9.0./8.0)-1.0)];
end
